// <auto-generated />
using System;
using ASP_Fund_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP_Fund_Project.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260316011539_AddBeneficiaryVerification")]
    partial class AddBeneficiaryVerification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASP_Fund_Project.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            Email = "admin@communityfundhub.local",
                            EmailConfirmed = true,
                            FullName = "Platform Administrator",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@COMMUNITYFUNDHUB.LOCAL",
                            NormalizedUserName = "ADMIN@COMMUNITYFUNDHUB.LOCAL",
                            PasswordHash = "AQAAAAIAAYagAAAAEFxuRvZxQm/vyVMytjxyb8RkvTTy6FwpftnnlpIAqG0SupBVNaciShn7W9j4//M+jA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            TwoFactorEnabled = false,
                            UserName = "admin@communityfundhub.local"
                        });
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.Beneficiary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAccountName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bic")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FocusArea")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Iban")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("ManagerUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Story")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerUserId");

                    b.ToTable("Beneficiaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BankAccountName = "Bright Path Youth Center",
                            BankName = "UniCredit Bulbank",
                            Bic = "UNCRBGSF",
                            City = "Sofia",
                            FocusArea = "After-school education",
                            FullName = "Bright Path Youth Center",
                            Iban = "BG80UNCR70001512345678",
                            IsVerified = false,
                            Kind = 2,
                            Story = "Bright Path supports teenagers from underserved neighborhoods with tutoring, mentoring, and digital literacy workshops throughout the school year."
                        },
                        new
                        {
                            Id = 2,
                            BankAccountName = "St. Marina Health Circle",
                            BankName = "DSK Bank",
                            Bic = "STSABGSF",
                            City = "Plovdiv",
                            FocusArea = "Community health",
                            FullName = "St. Marina Health Circle",
                            Iban = "BG48STSA93000012345678",
                            IsVerified = false,
                            Kind = 2,
                            Story = "St. Marina Health Circle organizes mobile screenings, medicine support, and care coordination for elderly residents who struggle to access regular treatment."
                        },
                        new
                        {
                            Id = 3,
                            BankAccountName = "Riverbank Arts Lab",
                            BankName = "Postbank",
                            Bic = "BPBIBGSF",
                            City = "Varna",
                            FocusArea = "Creative inclusion",
                            FullName = "Riverbank Arts Lab",
                            Iban = "BG30BPBI79401234567890",
                            IsVerified = false,
                            Kind = 2,
                            Story = "Riverbank Arts Lab runs free arts residencies and community events that help young creators turn talent into practical opportunities."
                        });
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.Contribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ContributorUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DonatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonorName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("FundingCampaignId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCommentHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDonationHidden")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContributorUserId");

                    b.HasIndex("FundingCampaignId");

                    b.ToTable("Contributions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 250m,
                            DonatedOn = new DateTime(2026, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Ivan Kolev",
                            Frequency = 1,
                            FundingCampaignId = 1,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Happy to support practical tech access.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 500m,
                            DonatedOn = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Nadya Hristova",
                            Frequency = 1,
                            FundingCampaignId = 2,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "For the mobile health visits.",
                            PaymentMethod = 1,
                            Status = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 120m,
                            DonatedOn = new DateTime(2026, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Petar Nikolov",
                            Frequency = 3,
                            FundingCampaignId = 3,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Excited to visit the exhibition.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 320m,
                            DonatedOn = new DateTime(2026, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Teodora Yaneva",
                            Frequency = 2,
                            FundingCampaignId = 1,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Education changes trajectories.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 85m,
                            DonatedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Kalin Georgiev",
                            Frequency = 1,
                            FundingCampaignId = 1,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Wishing the students a strong spring term.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 140m,
                            DonatedOn = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Maria Toncheva",
                            Frequency = 3,
                            FundingCampaignId = 1,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "For new learning equipment.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Amount = 60m,
                            DonatedOn = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Georgi Mihaylov",
                            Frequency = 1,
                            FundingCampaignId = 1,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Keep going.",
                            PaymentMethod = 1,
                            Status = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 210m,
                            DonatedOn = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Ralitsa Daneva",
                            Frequency = 1,
                            FundingCampaignId = 2,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Community care matters.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Amount = 95m,
                            DonatedOn = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Nikolay Velikov",
                            Frequency = 3,
                            FundingCampaignId = 2,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "For additional screening kits.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Amount = 180m,
                            DonatedOn = new DateTime(2026, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Violeta Hristova",
                            Frequency = 2,
                            FundingCampaignId = 2,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Proud of this work.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Amount = 70m,
                            DonatedOn = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Anton Marinov",
                            Frequency = 1,
                            FundingCampaignId = 3,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Art access should be public.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Amount = 130m,
                            DonatedOn = new DateTime(2026, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Silvia Stoyanova",
                            Frequency = 3,
                            FundingCampaignId = 3,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "For the materials budget.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Amount = 55m,
                            DonatedOn = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Kristian Popov",
                            Frequency = 1,
                            FundingCampaignId = 3,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Looking forward to the studio week.",
                            PaymentMethod = 1,
                            Status = 3
                        },
                        new
                        {
                            Id = 14,
                            Amount = 45m,
                            DonatedOn = new DateTime(2026, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Monika Petkova",
                            Frequency = 1,
                            FundingCampaignId = 1,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Happy to support this cause.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            Amount = 160m,
                            DonatedOn = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Stefan Iliev",
                            Frequency = 1,
                            FundingCampaignId = 2,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "From our family to yours.",
                            PaymentMethod = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = 16,
                            Amount = 110m,
                            DonatedOn = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DonorName = "Desislava Vasileva",
                            Frequency = 2,
                            FundingCampaignId = 3,
                            IsCommentHidden = false,
                            IsDonationHidden = false,
                            Note = "Supporting local creativity.",
                            PaymentMethod = 2,
                            Status = 1
                        });
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.FundingCampaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeneficiaryId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GoalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeletionRequested")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<string>("OrganizerName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.HasKey("Id");

                    b.HasIndex("BeneficiaryId");

                    b.HasIndex("OwnerId");

                    b.ToTable("FundingCampaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeneficiaryId = 1,
                            Category = 1,
                            CreatedOn = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentAmount = 8450m,
                            EndDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalAmount = 12000m,
                            IsApproved = true,
                            IsDeletionRequested = false,
                            IsFeatured = true,
                            IsHidden = false,
                            OrganizerName = "Mila Petrova",
                            OwnerId = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            StartDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "A focused campaign to equip Bright Path students with refurbished laptops and internet vouchers for project-based learning.",
                            Title = "Laptop Library for Future Coders"
                        },
                        new
                        {
                            Id = 2,
                            BeneficiaryId = 2,
                            Category = 2,
                            CreatedOn = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentAmount = 11200m,
                            EndDate = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalAmount = 18000m,
                            IsApproved = true,
                            IsDeletionRequested = false,
                            IsFeatured = true,
                            IsHidden = false,
                            OrganizerName = "Dragan Iliev",
                            OwnerId = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            StartDate = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Funding one season of neighborhood screenings, blood pressure kits, and medication tracking support for homebound seniors.",
                            Title = "Mobile Screenings for Seniors"
                        },
                        new
                        {
                            Id = 3,
                            BeneficiaryId = 3,
                            Category = 5,
                            CreatedOn = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CurrentAmount = 3900m,
                            EndDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GoalAmount = 9000m,
                            IsApproved = true,
                            IsDeletionRequested = false,
                            IsFeatured = false,
                            IsHidden = false,
                            OrganizerName = "Elena Georgieva",
                            OwnerId = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "A public-facing arts week that gives emerging creators materials, exhibition space, and mentoring from local professionals.",
                            Title = "Open Studio Week for Young Artists"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "af6f1f0d-5482-45c4-84dc-8d4c7ec9d001",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "8cf2c7fc-3277-4bff-bc66-14f05fc4a001",
                            RoleId = "af6f1f0d-5482-45c4-84dc-8d4c7ec9d001"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.Beneficiary", b =>
                {
                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", "ManagerUser")
                        .WithMany("ManagedBeneficiaries")
                        .HasForeignKey("ManagerUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ManagerUser");
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.Contribution", b =>
                {
                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", "ContributorUser")
                        .WithMany("Contributions")
                        .HasForeignKey("ContributorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ASP_Fund_Project.Models.FundingCampaign", "FundingCampaign")
                        .WithMany("Contributions")
                        .HasForeignKey("FundingCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContributorUser");

                    b.Navigation("FundingCampaign");
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.FundingCampaign", b =>
                {
                    b.HasOne("ASP_Fund_Project.Models.Beneficiary", "Beneficiary")
                        .WithMany("FundingCampaigns")
                        .HasForeignKey("BeneficiaryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", "Owner")
                        .WithMany("CreatedCampaigns")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Beneficiary");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ASP_Fund_Project.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.ApplicationUser", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("CreatedCampaigns");

                    b.Navigation("ManagedBeneficiaries");
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.Beneficiary", b =>
                {
                    b.Navigation("FundingCampaigns");
                });

            modelBuilder.Entity("ASP_Fund_Project.Models.FundingCampaign", b =>
                {
                    b.Navigation("Contributions");
                });
#pragma warning restore 612, 618
        }
    }
}
